/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fel5418' at '8/17/16 9:55 PM' with Gradle 2.14
 *
 * @author fel5418, @date 8/17/16 9:55 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
